### ISSUE TITLE
Issue for general implementation discussion

### ISSUE THREAD

**Issue by seijihariki** [zero01101/openOutpaint-webUI-extension#1] opened 2022-12-18 22:36 UTC
This is an issue just for general implementation discussion for this repo.

This should be closed when we have a working prototype of the extension, with automatic setting of host set and maybe a simple image send button from txt2img to openOutpaint resource.

**Comment by zero01101** [comment] 2022-12-18 23:00
current known issues:
 - must add "http://localhost:7860" to allowed CORS origins which is kinda lulzy, it doesn't trust itself tee hee hee
 - hardcoded 1024px height because 100% was a _filthy liar_
 - all the broken images :( 
 - gotta manually click the dream tool to get the reticle to show up when switching to the tab the first time

**Comment by seijihariki** [comment] 2022-12-18 23:11
> current known issues:
>  - must add "http://localhost:7860" to allowed CORS origins which is kinda lulzy, it doesn't trust itself tee hee hee

Hm... Have you tried accessing the webui via localhost:7860 instead of 127.0.0.1:7860? This seems like it would fix this issue. It would be great if the extension automatically checked this for us though.

>  - hardcoded 1024px height because 100% was a _filthy liar_

100% is regarding parent, and if parent has no obligation to be large then it will be small anyways... We will probably have to calculate the height manually for this tab. Either with css calc() or with JavaScript.

>  - all the broken images :( 

Is this on local hosting or github pages still?

>  - gotta manually click the dream tool to get the reticle to show up when switching to the tab the first time

If you click, is a dream still created?

**Comment by zero01101** [comment] 2022-12-19 00:04
>Hm... Have you tried accessing the webui via localhost:7860 instead of 127.0.0.1:7860?

hilariously, i AM using localhost:7860 :D 

>100% is regarding parent, and if parent has no obligation to be large then it will be small anyways...

🤦 i probably shoulda known that lol

images are fixed now :D 

>If you click, is a dream still created?

ooh, interesting; nope, it sure isn't

lol new minor issue:
- canvas resolution config is, uh.... broken
![image](https://user-images.githubusercontent.com/1649724/208326573-0801a7b8-f320-46ea-ae58-7e93299114c1.png)

**Comment by zero01101** [comment] 2022-12-19 00:22
bet this is sure relevant about the "manually choose dream reticle" thing 
![image](https://user-images.githubusercontent.com/1649724/208327303-265fcb0d-ea17-4b3c-86ef-1b45b8f73274.png)

**Comment by seijihariki** [comment] 2022-12-19 03:09
> bet this is sure relevant about the "manually choose dream reticle" thing ![image](https://user-images.githubusercontent.com/1649724/208327303-265fcb0d-ea17-4b3c-86ef-1b45b8f73274.png)

Seems this is a known bug in Firefox, in which operations on contexts located in hidden iframes fail:

https://bugzilla.mozilla.org/show_bug.cgi?id=941146
https://bugzilla.mozilla.org/show_bug.cgi?id=733698

Added fix from https://gist.github.com/subzey/2030480 to pull https://github.com/zero01101/openOutpaint/pull/110 ([c1614ed](https://github.com/zero01101/openOutpaint/pull/110/commits/c1614edf996023e1b72adece0c3d65a3ceb8aa6d))

**Comment by seijihariki** [comment] 2022-12-19 03:12
> current known issues:
> 
>     * must add "http://localhost:7860" to allowed CORS origins which is kinda lulzy, it doesn't trust itself tee hee hee

Cannot replicate this first issue, unless I access webui via localhost:7860 and try using host 127.0.0.1:7860 or the reverse.

**Comment by zero01101** [comment] 2022-12-19 04:47
>Cannot replicate this first issue, unless I access webui via localhost:7860 and try using host 127.0.0.1:7860 or the reverse.

🤦 welp considering i use localhost:7860 for webUI and 127.0.0.1:7860 for openOutpaint host value, uh, yeah that'd make perfect sense lmao

**Comment by zero01101** [comment] 2022-12-19 05:40
i would just like to say i agree with pylint 🎬 

https://github.com/zero01101/openOutpaint-webUI-extension/actions/runs/3728764208/jobs/6324047629#step:5:31

**Comment by seijihariki** [comment] 2022-12-19 20:52
Everything should be working now.

**Comment by zero01101** [comment] 2022-12-19 23:25
holy crap, seems uhhh a bunch has happened since i last checked lol, this is insane, just trying to not force the height in the gradio tab was driving me absolutely batty last night and here you've done... uh... everything :D

**Comment by seijihariki** [comment] 2022-12-19 23:39
Not really everything, just the basics of the thing, probably. I think we could add a lot before actually considering this done (better integration with the UI in general would be quite interesting).

**Comment by zero01101** [comment] 2022-12-20 02:02
>Not really everything, just the basics of the thing, probably

lmaoooo i'm sorry, you've been cleaning up my mess for _HOW LONG NOW_ 

"the basics" === IT'S DONE lol, minimum viable product gets SHIPPED

move fast break things™

**Comment by ClashSAN** [comment] 2022-12-22 21:23
thanks for this. installing this extension from url will not install the app folder currently. having `install.py` should help with this.

**Comment by zero01101** [comment] 2022-12-22 23:00
hey @ClashSAN, much obliged for taking a look at it :) 

yeah, at the moment it doesn't check out the submodule until webUI is restarted and the script is initialized; the call to `scripts.basedir()` returns the webUI installation directory if called from install.py instead of the extension's directory if called from a file within `scripts`, so getting the submodule contents on tab init instead of install seemed to be the most bulletproof way to do so.  

if that's still an issue we can keep looking for a workaround; i looked at several other extensions' install.py files and didn't see any of them pulling in git submodules at that stage but definitely can't say i checked all the other extensions scripts :/

**Comment by ClashSAN** [comment] 2022-12-22 23:27
it was an issue at my end, my folder had spaces lol
eg: Dec 21 2022\stable-diffusion-webui
if anyone else has the issue tell them to rename it with underscores

**Comment by ClashSAN** [comment] 2022-12-22 23:29
> hey @ClashSAN, much obliged for taking a look at it :)
> 
> ~yeah, at the moment it doesn't check out the submodule until webUI is restarted and the script is initialized; the call to `scripts.basedir()` returns the webUI installation directory if called from install.py instead of the extension's directory if called from a file within `scripts`, so getting the submodule contents on tab init instead of install seemed to be the most bulletproof way to do so.~
> 
> ~if that's still an issue we can keep looking for a workaround; i looked at several other extensions' install.py files and didn't see any of them pulling in git submodules at that stage but definitely can't say i checked all the other extensions scripts :/~
> 
> ha ha ha never mind all that, submodule clones in install.py now :D

great, confirmed i see the tab and the ui

**Comment by zero01101** [comment] 2022-12-22 23:43
lol python _really_ dislikes spaces in paths it seems :) thanks!

**Comment by zero01101** [comment] 2022-12-22 23:54
pushed a little commit adding double quote characters surrounding the path to hopefully alleviate spaces being an issue :)

**Comment by Lesteriax** [comment] 2022-12-26 10:50
Small suggestion: If we're generating more than 1 batch/iteration, let's say 4 for this example. Instead of waiting for all 4 to complete, is it possible to first show the first result then continue loading other batches/iterations? While checking the results, which might work on the first try, other iterations/batches would be loading in the background.

**Comment by seijihariki** [comment] 2022-12-26 12:26
We are currently using the iterations parameter of the API to provide this feature, so it would not be possible... But we can migrate this feature to use our own iteration system to implement something like that.

Though this could impact generation performance quite a bit if images are generated too fast and internet is too slow.

**Closed** 2023-01-13 15:06 UTC

**Comment by bojanm1972** [comment] 2023-01-28 21:54
I did something wrong.
I installed extension as usual. I add --api in start file, All happen as it need. I get new tab OpenOutpainting, interface works, but I constantly have following:
2openoutpaint-ext.js?1674929564.5171092:184 [openoutpaint] Sending init message
webui.js?v=8edac89:81 
        
       [webui] Message with incorrect key was received from 'http://127.0.0.1:7860'
(anonymous) @ webui.js?v=8edac89:81
postMessage (async)
sendInit @ openoutpaint-ext.js?1674929564.5171092:191
setTimeout (async)
sendInit @ openoutpaint-ext.js?1674929564.5171092:222
setTimeout (async)
sendInit @ openoutpaint-ext.js?1674929564.5171092:222
setTimeout (async)
sendInit @ openoutpaint-ext.js?1674929564.5171092:222
setTimeout (async)
sendInit @ openoutpaint-ext.js?1674929564.5171092:222
setTimeout (async)
sendInit @ openoutpaint-ext.js?1674929564.5171092:222
setTimeout (async)
sendInit @ openoutpaint-ext.js?1674929564.5171092:222
setTimeout (async)
sendInit @ openoutpaint-ext.js?1674929564.5171092:222
setTimeout (async)
sendInit @ openoutpaint-ext.js?1674929564.5171092:222
setTimeout (async)
sendInit @ openoutpaint-ext.js?1674929564.5171092:222
setTimeout (async)
sendInit @ openoutpaint-ext.js?1674929564.5171092:222
setTimeout (async)
sendInit @ openoutpaint-ext.js?1674929564.5171092:222
setTimeout (async)
sendInit @ openoutpaint-ext.js?1674929564.5171092:222
setTimeout (async)
sendInit @ openoutpaint-ext.js?1674929564.5171092:222
webui.js?v=8edac89:84 
        
       {type: 'openoutpaint/init', key: 'M3VsHXkrZdqrPBeXwkvF', host: 'http://127.0.0.1:7860', destinations: Array(6)}
(anonymous) @ webui.js?v=8edac89:84
postMessage (async)
sendInit @ openoutpaint-ext.js?1674929564.5171092:191
setTimeout (async)
sendInit @ openoutpaint-ext.js?1674929564.5171092:222
setTimeout (async)
sendInit @ openoutpaint-ext.js?1674929564.5171092:222
setTimeout (async)
sendInit @ openoutpaint-ext.js?1674929564.5171092:222
setTimeout (async)
sendInit @ openoutpaint-ext.js?1674929564.5171092:222
setTimeout (async)
sendInit @ openoutpaint-ext.js?1674929564.5171092:222
setTimeout (async)
sendInit @ openoutpaint-ext.js?1674929564.5171092:222
setTimeout (async)
sendInit @ openoutpaint-ext.js?1674929564.5171092:222
setTimeout (async)
sendInit @ openoutpaint-ext.js?1674929564.5171092:222
setTimeout (async)
sendInit @ openoutpaint-ext.js?1674929564.5171092:222
setTimeout (async)
sendInit @ openoutpaint-ext.js?1674929564.5171092:222
setTimeout (async)
sendInit @ openoutpaint-ext.js?1674929564.5171092:222
setTimeout (async)
sendInit @ openoutpaint-ext.js?1674929564.5171092:222
setTimeout (async)
sendInit @ openoutpaint-ext.js?1674929564.5171092:222

W
![Screenshot_20230128_105304](https://user-images.githubusercontent.com/3257555/215292815-e1e4c308-78bc-4a47-bf01-8dd38e2cd6ed.png)
hat I am doing wrong here?

**Comment by zero01101** [comment] 2023-01-29 05:24
@bojanm1972 definitely looks like openOutpaint and webUI had a mishap with the messaging between them; possibly try closing/restarting webUI, refreshing that page without cache, and trying again?  if it still occurs and you can reliably reproduce it, please open a new issue - thanks!
