### ISSUE TITLE
"index.html does not exist" but it does.

### ISSUE THREAD

**Issue by createperhaps** [zero01101/openOutpaint-webUI-extension#10] opened 2022-12-26 20:44 UTC
**Describe the bug**
When I click the openoutpaint tab I see Internal Server Error. The log says "index.html does not exist" but it does.

**To Reproduce**
I ran TheLastBen colab. 
 I click the extensions tab and scroll to openOutpaint
Click "install". Click "refresh GUI".
Go to the openOutpaint tab.
"internal server error" is displayed.

**Expected behavior**
I expect to see the outpaint GUI.

**Screenshots**

**Comment by seijihariki** [comment] 2022-12-26 21:27
Hello, this is an issue that _technically_ already existed, but on the main openOutpaint repo. I will be closing it as a duplicate of #11, which was transferred from there, but will be quoting this issue because it provides a more clear path for reproducing the bug.

**Closed by seijihariki** 2022-12-26 21:27 UTC
Labels: bug
