### ISSUE TITLE
[Bug] Outpaint black image

### ISSUE THREAD

**Issue by Rogal80** [zero01101/openOutpaint-webUI-extension#3] opened 2022-12-23 13:25 UTC
Hi, maybe I am doing something wrong – but no matter how many times I use the dream for outpaint i have always black image 

![image](https://user-images.githubusercontent.com/112553453/209343435-539a9aaa-cc47-4ac9-a8b3-08707982e08f.png)

any clue? ( inpainting mask is set on 1)

**Comment by zero01101** [comment] 2022-12-23 13:46
hm, not familiar with that model you're using, is it an inpainting model?   or maybe is it based off of a v2 model? i believe people have ran into that kind of thing with SD/webUI directly with v2 models -  might be worth disabling `--no-half` in your webui-user script, or maybe installing [DH patches extension](https://github.com/d8ahazard/sd_auto_fix) to see if it still occurs.

does that occur if you use the [runwayML inpainting model](https://huggingface.co/runwayml/stable-diffusion-inpainting/tree/main)?

**Comment by Rogal80** [comment] 2022-12-23 13:49
This is inpainting model merged with others, but also I tried with base 1.5 inpaint model – same results

**Comment by Rogal80** [comment] 2022-12-23 13:50
I already removed Outpaint from extension and reinstall but nothing happen – same issue, and after reinstall setting wasn't default

**Comment by zero01101** [comment] 2022-12-23 14:02
have you tried any of these commandline flags?  particularly `--medvram`/`--lowvram` and `--no-half`

https://www.reddit.com/r/StableDiffusion/comments/zhni48/just_installed_sd_but_it_keeps_giving_me_a_black/izn31no/

https://www.reddit.com/r/StableDiffusion/comments/zfa43l/black_image_when_using_sd_21_when_using/izb828d/?context=1

**Comment by Rogal80** [comment] 2022-12-23 14:08
i have 3090 and i am using this set COMMANDLINE_ARGS=--xformers --allow-code --api --listen --enable-insecure-extension-access --gradio-img2img-tool editor

**Comment by zero01101** [comment] 2022-12-23 14:19
huh... well you've definitely got the hardware for it; i've never ran into this and you're the first to report such things happening, but i'm still pretty certain it's more of an SD/webUI thing than openOutpaint just because we don't actually do _any_ image generation or processing, just send API calls to webUI and then manipulate the results it delivers...

https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/5757#issuecomment-1356054255 mentions that it could be an issue with the VAE but also specifies high resolutions, and you're using 512x512... might be worth trying anyway?  sorry i don't have a "oh yeah simple fix, just do x y z" for you :/

**Comment by Rogal80** [comment] 2022-12-23 14:22
anyway thx - inpainting works perfectly :)

**Comment by Rogal80** [comment] 2022-12-23 14:25
How can I reinstall? That will be like fresh extension because removing folder and reinstall still keeps old settings

**Comment by zero01101** [comment] 2022-12-23 14:31
openOutpaint saves a few settings to your browser's localstorage (and indexedDB if you've imported or created any stamp resources) - if you open the "debug settings" menu there's a "reset to defaults" button that clears the localstorage (and indexedDB if there are any) records, and after that removing the openOutpaint-webUI-extension folder should be pretty much it.  nothing gets added to your python venv or anything of that nature

**Comment by Rogal80** [comment] 2022-12-23 14:44
thx

**Comment by seijihariki** [comment] 2022-12-24 01:04
@Rogal80 is it working now?

**Comment by Rogal80** [comment] 2022-12-24 09:49
Hi, still same : 
![image](https://user-images.githubusercontent.com/112553453/209430509-6eda0868-2637-4f52-9278-6d7967ad9f27.png)

**Comment by seijihariki** [comment] 2022-12-24 14:58
I have sent some debugging tools to the main branch. Update the extension, enable debug in Debug Info tab, and try again.

Send us the resulting debugging image for the outpaint attempt.

**Comment by Lesteriax** [comment] 2022-12-26 10:43
I'm having the same issue, I thought I was doing something wrong with the openOutpaint sittings. 

Using img2img always gives me black results when trying to outpaint using vanilla inpaint1.5
![openOutpaint_debug_Mon Dec 26 2022 13_42_59 GMT+0300 (Arabian Standard Time)](https://user-images.githubusercontent.com/95050087/209539941-84c4bd77-d841-4f44-9b14-94fe914a86eb.png)

I'm using paperpsace version, tried with and without --no-half and medvram.

below screenshot and i also attached the debug image

![image](https://user-images.githubusercontent.com/95050087/209539294-52cca862-f9ae-4020-9fcf-4b58edf05232.png)

**Comment by seijihariki** [comment] 2022-12-26 11:16
Oh, outpainting almost always requires a 1 for denoising, as less than that will keep quite a lot of black pixels on the non-image part of the image. (Transparent pixels are sent as black to stable diffusion, as it can't really handle transparency)

Worse still, keep border gradient keeps the full black outline on the transparent areas, so stable diffusion sees the image with literally half of it black and extrapolates that it is indeed half-black.

For outpainting, it is recommended to use the dream tool instead of the img2img one. It always uses 1 as denoising strength, and automatically masks things to keep current imagery as is, and generates on transparent pixels.

**Comment by Rogal80** [comment] 2022-12-26 11:25
hi, debug output :
![openOutpaint_debug_Mon Dec 26 2022 12 24 08 GMT+0100 (Central European Standard Time)](https://user-images.githubusercontent.com/112553453/209543747-e4ff0cd2-8145-465f-baa2-fcaae3f466b3.png)

**Comment by seijihariki** [comment] 2022-12-26 11:37
That's... Very weird. Top should be image sent, bottom should be mask, as shown in Lesteriax's.

If they are both showing the original image, makes sense that the black area is continuing to be black...

@zero01101 maybe is some globalComposite weirdness?

**Comment by seijihariki** [comment] 2022-12-26 11:38
@Rogal80 what browser are you using?

**Comment by Rogal80** [comment] 2022-12-26 12:39
Firefox, windows 10

**Comment by Rogal80** [comment] 2022-12-26 12:42
I notice that in chrome it's working, is there any chance to fix this in Firefox :
![image](https://user-images.githubusercontent.com/112553453/209550282-b7fba5bb-0658-4ff1-9196-dc818b11f8bc.png)
![openOutpaint_debug_Mon Dec 26 2022 13_42_34 GMT+0100 (Central European Standard Time)](https://user-images.githubusercontent.com/112553453/209550320-e2d00240-e6ca-4783-8457-aca00c80eb7c.png)

**Comment by Lesteriax** [comment] 2022-12-26 13:10
Dreaming can do outpaintng as opposed to img2img.

problem with with dream is that outpainting produces weird results. I tried the monalisa and prompted for a painting with a beautiful woman and it gave me 3 headed monalisa.

**Comment by zero01101** [comment] 2022-12-26 14:53
>@zero01101 maybe is some globalComposite weirdness?

¯\_(ツ)_/¯ yeah, that is just _bonkers_; i'm still entirely unable to reproduce this myself 

>problem with with dream is that outpainting produces weird results. I tried the monalisa and prompted for a painting with a beautiful woman and it gave me 3 headed monalisa.

@Lesteriax were you using the auto HRfix option when using that?  that sounds more like the common SD issue with generating images that aren't exactly the dimensions of the training data more than anything else...

**Comment by seijihariki** [comment] 2022-12-29 16:11
Hi, @Rogal80. Sorry for the late response. Can you send us a screenshot of the result of running the following W3Schools example on your firefox browser:

https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_canvas_globalcompop_all

This is the expected result:
![image](https://user-images.githubusercontent.com/7552751/209979797-880bb2a3-5005-4426-9f0e-681b9d7e4f44.png)

**Comment by rivermonster** [comment] 2022-12-29 21:51
Switching to Chrome solved the same issue for me that I was getting in Firefox.

**Comment by zero01101** [comment] 2022-12-29 23:08
i almost exclusively use firefox and honestly can't get this to happen for the life of me; even gone as far as manually installing the NSFW check extension to see if maybe that was inadvertently getting triggered or something but no luck... 

@Rogal80 and @rivermonster, are either of you using any firefox addons?  [it seems that the microsoft editor extension for chrome gets into fights with the automask slider](https://github.com/zero01101/openOutpaint/discussions/88#discussioncomment-4498341) which is genuinely an incompatibility i can say i could never have predicted... also, along with the canvas GCO test @seijihariki mentioned, could i possibly ask if you'd mind trying (preferably both) webUI and the extension, or just standalone openOutpaint in a [firefox troubleshooting state](https://support.mozilla.org/en-US/kb/troubleshoot-extensions-themes-to-fix-problems#w_start-firefox-in-troubleshoot-mode) and seeing if that makes a difference?

**Comment by rivermonster** [comment] 2022-12-30 02:10
Got it!

Figured it out, it's a two variable problem so it was annoying to isolate it. The issue *TRIGGERED* for me is experienced ONLY when BOTH of the follow are TRUE:

1. The extension DuckDuckGo Privacy Essentials is active
2. The theme is set to Dark space - The Best Dynamic Theme
Once this is the case then only by turning off both and reloading the webui can I get things working properly again.

Hope this helps replicate and narrow it down!

**Comment by zero01101** [comment] 2022-12-30 02:29
FASCINATING

will see if i can confirm

**Comment by zero01101** [comment] 2022-12-30 02:31
![image](https://user-images.githubusercontent.com/1649724/210028626-76c42617-eefa-4b38-a688-aa1650a5af46.png)

added duckduckgo privacy addon, left default settings, simply tried to outpaint and... yep, busted

thank you greatly for your findings

**Comment by zero01101** [comment] 2022-12-30 02:39
confirmed on openOutpaint standalone as well, and obnoxiously the GCO test showed nothing out of the ordinary at all
![image](https://user-images.githubusercontent.com/1649724/210029016-f93b2239-948d-47fc-9ece-a32ce3993a47.png)

**Comment by zero01101** [comment] 2022-12-30 02:44
it says that "privacy protections aren't available for special pages or local pages" in the option menu, but if i manually add localhost to the unprotected sites list, outpainting works again - @rivermonster could you try that? 
![image](https://user-images.githubusercontent.com/1649724/210029285-d3d2bbcc-091d-4b9b-8e18-fb6a93ac50ad.png)

**Comment by rivermonster** [comment] 2022-12-30 02:54
@zero01101 Can confirm that adding 127.0.0.1 to the unprotected sites list fixed the issue and allowed the extension to remain enabled.

Also, thanks so much for this extension. You guys really are my heroes!

**Comment by zero01101** [comment] 2022-12-30 04:13
aww :3 just glad to figure it out lol, was driving me absolutely batty :D 

added mentions to the readmes, will update docs eventually

**Comment by zero01101** [comment] 2022-12-30 04:14
@Rogal80 any chance you could test this out, assuming you're using the duckduckgo extension as well?

**Comment by Rogal80** [comment] 2022-12-30 10:07
Hi, sorry for late response,
![image](https://user-images.githubusercontent.com/112553453/210058411-96b26e94-0936-42d5-8dfb-f0bd0d9c8d32.png)
 I am also using Firefox extension:
— language tool 
— dark reader, but it's off on webui
— easy YouTube video downloader
— DuckDuckGo
— Search by Image

**Comment by Rogal80** [comment] 2022-12-30 10:14
Ok, found it, it's dark reader causing issue – disabling it for whole Firefox it's fixing outpaint

**Comment by seijihariki** [comment] 2022-12-30 11:08
Okay, thank you for your report! Added some instructions on the README for debugging extension issues the next time something is very weird, like in this issue.

**Comment by seijihariki** [comment] 2022-12-30 11:09
Will be closing this issue now.

**Closed** 2022-12-30 11:09 UTC
Labels: bug, eval, external

**Comment by fhnb16** [comment] 2023-01-28 10:57
Get this issue in Edge (chromium) and Firefox without any extentions, img2img produce blank black image(

**Comment by zero01101** [comment] 2023-01-28 15:21
@fhnb16 the img2img tool will result in black pixels when used over empty/transparent space unlike the dream tool, is that what you're referencing?
